name: att
on: [push]
jobs:
  att:
    runs-on: ubuntu-latest
    steps:
      - name: whoami
        uses: fifsky/ssh-action@master
        with:
          command: |
            whoami
            ls
          host: ${{ secrets.HOST }}
          user: root
          key: ${{ secrets.PRIVATE_KEY}}
