name: att
on: [push]
jobs:
  att:
    runs-on: ubuntu-latest
    steps:
      - name: whoami
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: whoami
          host: ${{ secrets.HOST }}
          username: root
          privateKey: ${{ secrets.PRIVATE_KEY}}
