name: att
on: [push]
jobs:
  att:
    runs-on: ubuntu-latest
    steps:
      - name: whoami
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /try/try1234
            git pull
          #command: |
          #  whoami
          #  ls
          #  mkdir /thisisit1234
          host: ${{ secrets.HOST }}
          user: root
          key: ${{ secrets.PRIVATE_KEY}}
